--- 
abstract: push more than one character back onto a filehandle
author: 
  - Ben Morrow <ben@morrow.me.uk>
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: IO-Unread
no_index: 
  directory: 
    - inc
    - t
requires: 
  perl: 5.8.1
version: 1.03
